platform:
  database:
    globalschema: BIZX
    dedicatedSchema: false
    datasources:
       - name: dbPool1
         url: jdbc:1
         username: PLUMBER_BIZX
         password: Pass1234
         hikari.maximumPoolSize: 20
       - name: dbPool2
         url: jdbc:2
         username: BIZX
         password: Pass1234
       - name: dbPool2
         url: jdbc:3
         username: PLUMBER_BIZX_PROVISIONER
         password: Pass1234
         group: provision
